import Head from 'next/head'
import {Box, VStack, Text, HStack, Divider, Input, Spacer} from "@chakra-ui/react";
import QueueTable from "@/components/QueueTable";
import UserTable from "@/components/UserTable";
import {ChangeEvent, useState} from "react";

export default function Home() {
    const [queues, setQueues] = useState(undefined);

    const handleFileUpload = (event: ChangeEvent<HTMLInputElement>) => {
        // @ts-ignore
        const file = event.target.files[0];

        const reader = new FileReader();
        reader.onload = (e) => {
            try {
                // @ts-ignore
                const fileContent = e.target.result;
                // @ts-ignore
                const parsedQueues = JSON.parse(fileContent);
                setQueues(parsedQueues);
            } catch (error) {
                console.error('Error parsing JSON file:', error);
            }
        };

        reader.readAsText(file);
    };

    return (
        <>
            <Head>
                <title>Hours Data Explorer</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <VStack maxW="5xl" mx="auto" alignItems="start" py={10} spacing={10}>
                    <Text fontSize="3xl" fontWeight="bold">
                        Hours Data Explorer
                    </Text>
                    {!queues ? <Box rounded="xl" borderWidth={1} borderColor="gray.300" width="100%">
                        <HStack p={4}>
                            <Text fontSize="lg" fontWeight="semibold">
                                Upload JSON dump file
                            </Text>
                            <Spacer/>
                            <input type="file" accept=".json" onChange={handleFileUpload}/>
                        </HStack>
                    </Box> : <>
                        <Box rounded="xl" borderWidth={1} borderColor="gray.300" width="100%">
                            <HStack p={4}>
                                <Text fontSize="lg" fontWeight="semibold">
                                    Queues
                                </Text>
                                <Spacer/>
                            </HStack>
                            <Divider/>
                            <QueueTable queues={queues} itemsPerPage={10}/>
                        </Box>

                        <Box rounded="xl" borderWidth={1} borderColor="gray.300" width="100%">
                            <HStack p={4}>
                                <Text fontSize="lg" fontWeight="semibold">
                                    Users
                                </Text>
                                <Spacer/>
                            </HStack>
                            <Divider/>
                            <UserTable queues={queues} itemsPerPage={10}/>
                        </Box>
                    </>}
                </VStack>


            </main>
        </>
    )
}